# fly.toml app configuration file generated for flaresolv-tabletki on 2023-10-02T14:45:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flaresolv-tabletki"
primary_region = "ams"

[http_service]
  internal_port = 8191
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
